//
// Created by jack on 10/13/20.
//

#ifndef BLINKYEXAMPLEPROJECT_SRC_COMPONENTS_DISPLAY_SETTINGS_DISPLAY_SETTINGS_H
#define BLINKYEXAMPLEPROJECT_SRC_COMPONENTS_DISPLAY_SETTINGS_DISPLAY_SETTINGS_H

typedef enum {
  SETTING_BUTTON,
  SETTING_SWITCH
} eDisplaySettingSelector;

void settings_screen(void);

#endif //BLINKYEXAMPLEPROJECT_SRC_COMPONENTS_DISPLAY_SETTINGS_DISPLAY_SETTINGS_H
