//
// Created by jack on 10/13/20.
//

#ifndef BLINKYEXAMPLEPROJECT_SRC_COMPONENTS_DISPLAY_BRIGHTNESS_DISPLAY_BRIGHTNESS_H
#define BLINKYEXAMPLEPROJECT_SRC_COMPONENTS_DISPLAY_BRIGHTNESS_DISPLAY_BRIGHTNESS_H

void brightness_screen(void);

#endif //BLINKYEXAMPLEPROJECT_SRC_COMPONENTS_DISPLAY_BRIGHTNESS_DISPLAY_BRIGHTNESS_H
