//
// Created by jack on 10/13/20.
//

#ifndef BLINKYEXAMPLEPROJECT_SRC_COMPONENTS_DISPLAY_STEPS_DISPLAY_STEPS_H
#define BLINKYEXAMPLEPROJECT_SRC_COMPONENTS_DISPLAY_STEPS_DISPLAY_STEPS_H

void steps_screen(void);


#endif //BLINKYEXAMPLEPROJECT_SRC_COMPONENTS_DISPLAY_STEPS_DISPLAY_STEPS_H
