SRC_FILES += lv_arc.c
SRC_FILES += lv_bar.c
SRC_FILES += lv_cb.c
SRC_FILES += lv_cpicker.c
SRC_FILES += lv_ddlist.c
SRC_FILES += lv_kb.c
SRC_FILES += lv_line.c
SRC_FILES += lv_mbox.c
SRC_FILES += lv_preload.c
SRC_FILES += lv_roller.c
SRC_FILES += lv_table.c
SRC_FILES += lv_tabview.c
SRC_FILES += lv_tileview.c
SRC_FILES += lv_btn.c
SRC_FILES += lv_calendar.c
SRC_FILES += lv_chart.c
SRC_FILES += lv_canvas.c
SRC_FILES += lv_gauge.c
SRC_FILES += lv_label.c
SRC_FILES += lv_list.c
SRC_FILES += lv_slider.c
SRC_FILES += lv_ta.c
SRC_FILES += lv_spinbox.c
SRC_FILES += lv_btnm.c
SRC_FILES += lv_cont.c
SRC_FILES += lv_img.c
SRC_FILES += lv_imgbtn.c
SRC_FILES += lv_led.c
SRC_FILES += lv_lmeter.c
SRC_FILES += lv_page.c
SRC_FILES += lv_sw.c
SRC_FILES += lv_win.c

DEPPATH += --dep-path $(LVGL_DIR)/lvgl/src/lv_objx
VPATH += :$(LVGL_DIR)/lvgl/src/lv_objx

CFLAGS += "-I$(LVGL_DIR)/lvgl/src/lv_objx"
