//
// Created by jack on 7/12/20.
//

#ifndef JDSMARTWATCHPROJECT_SRC_COMPONENTS_DISPLAY_DISPLAY_BOOT_UP_H
#define JDSMARTWATCHPROJECT_SRC_COMPONENTS_DISPLAY_DISPLAY_BOOT_UP_H

#include "lvgl/lvgl.h"

void display_boot_up(lv_obj_t * parent);

#endif //JDSMARTWATCHPROJECT_SRC_COMPONENTS_DISPLAY_DISPLAY_BOOT_UP_H
