//
// Created by jack on 9/19/20.
//

#ifndef BLINKYEXAMPLEPROJECT_SRC_COMPONENTS_DISPLAY_SCREENS_SIMPLE_TIME_H
#define BLINKYEXAMPLEPROJECT_SRC_COMPONENTS_DISPLAY_SCREENS_SIMPLE_TIME_H

void screen_simple_time(void);

#endif //BLINKYEXAMPLEPROJECT_SRC_COMPONENTS_DISPLAY_SCREENS_SIMPLE_TIME_H
