//
// Created by jack on 11/1/20.
//

#ifndef JD_SMARTWATCH_SRC_COMPONENTS_SETTINGS_SETTINGS_H
#define JD_SMARTWATCH_SRC_COMPONENTS_SETTINGS_SETTINGS_H

#endif //JD_SMARTWATCH_SRC_COMPONENTS_SETTINGS_SETTINGS_H
