//
// Created by jack on 11/8/20.
//

#ifndef JD_SMARTWATCH_SRC_APP_SYS_TASK_APP_SETTINGS_H
#define JD_SMARTWATCH_SRC_APP_SYS_TASK_APP_SETTINGS_H

#endif //JD_SMARTWATCH_SRC_APP_SYS_TASK_APP_SETTINGS_H
